# Gitlab CI
build:
  image: maven:3.6.3-openjdk-11
  services:
    - mysql:8.0

  variables:
    # Configure mysql environment variables (https://hub.docker.com/_/mysql/)
    MYSQL_DATABASE: "db_movie"
    MYSQL_ROOT_PASSWORD: "root"

  script:
    - mvn test