version: 2
jobs:
  test_app:
    docker:
      - image: circleci/openjdk:11.0.1-jdk
      - image: mysql:8.0
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: db_movie_test

    working_directory: ~/web-app

    steps:
      # setup testing env
      - setup_remote_docker:
          docker_layer_caching: true

      # git pull
      - checkout

      - save_cache:
          paths:
            - ~/.m2
          key: web-app-{{ checksum "pom.xml" }}

      # test project
      - run: mvn test

workflows:
  version: 2
  build_and_test:
    jobs:
      - test_app